# Site settings
title: Sarah Carl
email: sarahhcarl@gmail.com
url: https://sarahcarl.com
description: 
skills: "Bioinformatics - Genomics - Epigenetics"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Sarah Carl
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sarahhcarl
  - title: linkedin
    url: https://ch.linkedin.com/pub/sarah-carl/15/664/261
  - title: github
    url: http://github.com/sarahhcarl

# Postal address (add as many lines as necessary)
address:
  - line: Friedrich Miescher Institute
  - line: Maulbeerstrasse 66
  - line: 4058 Basel
  - line: Switzerland

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
